name: maps_up
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  image_picker: ^0.6.7+11
  #geolocator: any
  geolocator: ^5.1.0
  flutter_polyline_points: ^0.2.4
  flutter_google_places: ^0.2.6
  location: ^3.0.2
  url_launcher: ^5.7.2
  google_maps_flutter: any
  flutter_map: any
  google_maps_webservice: ^0.0.18
  http: ^0.12.2
  uuid: ^2.2.2
  provider: ^4.3.2+2
  geocoder: ^0.2.1
  # geoflutterfire: any
  material_floating_search_bar: ^0.1.7
  search_map_place: ^0.3.0
  google_place: ^0.3.3
  flutter_svg: ^0.17.3+1
  get_it: ^5.0.1
  shared_preferences: ^0.5.12+2
  flutter_spinkit: ^4.1.2+1
  flutter_staggered_grid_view: ^0.3.0
  coolors_palette: ^0.0.2
  
  #firebase
  firebase_auth: ^0.16.1
  firebase_core: any
  firebase_database: any
  cloud_firestore: any

  #login
  flutter_login_meetdeal: ^1.0.15

  flutter_unity_widget: ^2.0.0+2

  flutter_speed_dial: ^1.2.5

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - assets/icons/
    - assets/images/
    # - images/a_dot_ham.jpeg
    # - image/Logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pattaya
      fonts: 
        - asset: assets/fonts/Pattaya-Regular.ttf
        
          style: italic
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
